"""
Django settings for securetask project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# 1. Make sure these imports are at the very top of your settings.py (Line 1)
import os
from dotenv import load_dotenv
from pathlib import Path

# Load the variables from your .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# 2. Replace your original lines with these:
# ==========================================

# Pulls the string safely from your .env file
SECRET_KEY = os.getenv('SECRET_KEY')

# Reads the text 'True' and converts it into a real Python Boolean (True)
DEBUG = os.getenv('DEBUG') == 'True'

# Grabs '127.0.0.1,localhost' and splits it automatically into an array: ['127.0.0.1', 'localhost']
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'tasks',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'securetask.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'securetask.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# ==============================================================================
# STATIC FILES & SECURITY STORAGE CONFIGURATION
# ==============================================================================

# 1. Static Files Setup (WhiteNoise Configuration)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# 2. Secure Password Hashing (OWASP ASVS V3 / Section 5.1 Compliant)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

# ==============================================================================
# SESSION & COOKIE SECURITY HARKENING (OWASP ASVS V2 / Section 2 Compliant)
# ==============================================================================

# Prevents JavaScript from reading session cookies (Mitigates XSS cookie theft)
SESSION_COOKIE_HTTPONLY = True #CHANGE TO FALSE IF YOU ARE TESTING LOCALLY WITHOUT HTTPS
CSRF_COOKIE_HTTPONLY = True

# Forces cookies to only be sent over encrypted HTTPS connections
SESSION_COOKIE_SECURE = False #CHANGE TO FALSE IF YOU ARE TESTING LOCALLY WITHOUT HTTPS
CSRF_COOKIE_SECURE = False #CHANGE TO FALSE IF YOU ARE TESTING LOCALLY WITHOUT HTTPS

# Protects against Cross-Site Request Forgery (CSRF) attacks
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Session Timeout (As requested in Section 2: Sets session to expire when browser closes)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False